### ISSUE TITLE
Allow this to be installed via WoWup please

### ISSUE THREAD

**Issue by Poisonenvy2** [Starlynk1/IncognitoResurrected#1]
Hi.  Would it be possible to enable this to be downloaded somewhere other than Curse?  Could be wowinterface, wowuphub, wago or direct from Github.

More info can be found on WowUp's discord: https://discord.gg/DGsyTNtHt5

Thank you!

**Comment by Starlynk1** [comment]
I've made the request to WoWup Hub per their processs and haven't heard back yet. This was done about a week ago. Alternatively, you can use the WoWup-CF version and be able to pull from Curseforge and WoWup Hub.

**Comment by Starlynk1** [comment]
Had to do some adjustments and those have been done. I've requested it be added to WoWup Hub and just waiting for them to add it or tell me if I missed something again.

**Comment by Poisonenvy2** [comment]
Thank you.  I've asked them to look into it to .. apparently it's just waiting for one of them to add it manually.

**Comment by Starlynk1** [comment]
Addon has been added to WoWup
