### ISSUE TITLE
Lastest version dont load 1.0.6 [Bug]

### ISSUE THREAD

**Issue by amokiller** [Starlynk1/IncognitoResurrected#3]
Sorry im not english
**WoW Version**
Retail
  
**Describe the bug**
Last version (1.0.6) dont load. No show errors, only dont load. 

**To Reproduce**
Update to lastest version

Workarround:
1.0.5 version works fine

**Comment by Papaswigs** [comment]
Yes 1.0.6 is broken will not load

**Comment by Naragath** [comment]
There is a pretty easy fix:
Both of these fixes are in IncognitoResurrected.lua
On line 114 change it from:
InterfaceOptionsFrame_OpenToCategory(IncognitoResurrected.optionFrames.main),
to:
InterfaceOptionsFrame_OpenToCategory(IncognitoResurrected.optionFrames.main)
end,

After that go to line 122 and add a comma after "incognito"

After that it'll load just fine :)

**Comment by Poisonenvy2** [comment]
Errors from Bugsack, for info:

Error 1:

> 1x IncognitoResurrected/IncognitoResurrected.lua:114: unexpected symbol near ','
> 
> 
> Locals:
> 

Error 2:

> 2x IncognitoResurrected/IncognitoResurrected.lua:1 IncognitoResurrected/IncognitoResurrected.lua:114: unexpected symbol near ','

**Comment by Starlynk1** [comment]
Thanks for pointing this out, sorry. I missed a comma with my slashcmd update. New version coming shortly.
