### ISSUE TITLE
Configuration dialog does not appear [Bug]

### ISSUE THREAD

**Issue by nickylogic** [Starlynk1/IncognitoResurrected#4]
**WoW Version**
Retail
  
**Describe the bug**
The command "/incognito config" does not cause the dialog window to appear; it seems to have no effect at all.

**To Reproduce**
1. Install Incognito Resurrected
2. In Retail Wow, type "/incognito config"
3. Dialog window not opened

**Screenshots**
NA

**Additional context**
NA

**Comment by nickylogic** [comment]
LUA Error Log from "/incognito config"

```
Message: ...AddOns/IncognitoResurrected/IncognitoResurrected.lua:114: attempt to index field 'optionFrames' (a nil value)
Time: Tue Jul 30 20:26:02 2024
Count: 11
Stack: ...AddOns/IncognitoResurrected/IncognitoResurrected.lua:114: attempt to index field 'optionFrames' (a nil value)
[string "@Interface/AddOns/IncognitoResurrected/IncognitoResurrected.lua"]:114: in function <...AddOns/IncognitoResurrected/IncognitoResurrected.lua:113>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Recount/Libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:136: in function <.../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:126>
[string "@Interface/AddOns/Recount/Libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:401: in function <.../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:327>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Recount/Libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:762: in function `HandleCommand'
[string "@Interface/AddOns/IncognitoResurrected/Libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:781: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'optionFrames' (a nil value)"
```

**Comment by Starlynk1** [comment]
Thanks for the report, I am working on it. You can still go to the Options > Addons and adjust config that way until it is resolved.

**Comment by Starlynk1** [comment]
Update has been released for this issue. v1.0.17
Should show up on Curseforge and WowUp soon.

**Comment by nickylogic** [comment]
@Starlynk1 thanks very much for responding and for supporting this addon for the community.    With your latest update I don't see any script errors when typing "/incognito config" so that part is fixed.  It now jumps to the Options interface as intended.

What's strange, though, is that Incognito Resurrected isn't listed under Options > Addons.  This occurs even when I turn off all other addons.  I noticed a different error occurs when I reload UI, which someone has already reported as another issue.  Maybe your addon doesn't get registered in Options because of that error?
