### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Shazza-M-1993** [Starlynk1/IncognitoResurrected#6]
**WoW Version**
Retail

I have downloaded and installed it, doing everything correct. My guild mates even said I was doing everything correct and yet it does not appear to work for me. I have included screenshots to show you I have done everything correctly. Even showing that my fellow guild mates have theirs working. 

![WoWScrnShot_100424_130533](https://github.com/user-attachments/assets/0e13e4af-39b4-4b3c-888c-0cd1b3500c54)
![WoWScrnShot_100424_130545](https://github.com/user-attachments/assets/3dec164e-6e40-4f1d-b37a-b233831fa0b5)

**Comment by Starlynk1** [comment]
Are you getting any errors and do you have BugGrabber/BugSack installed?

Also, try adding Party and Raid to see if anything changes. Should work with just guild, but for testing we can see if those affect anything.

**Comment by Starlynk1** [comment]
I added the addons you have and checked them for any conflicts, couldn't find anything that would cause a problem and it worked with no issues. Right now, I would say this is something possibly that didn't install correctly when you initially installed. Please uninstall, go to your addons folder and remove the Incognito folder if it still exists. Make sure the game is closed and reinstall.

**Comment by Shazza-M-1993** [comment]
Hiya I done what you suggested and selected Instance, Raid etc are they work perfectly fine but the Guild option isn't working at all. Is there anything that I have missed regarding the Guild part. Even my Guild mates are stumped at why this wont work

**Comment by Starlynk1** [comment]
That is very strange and honestly not sure why it wouldn't show. Next steps would be to disable all addons and have only Incognito running. If it works with no other addons loaded, then it's a conflict with another addon.

Let me know what you find and we will go from there.

**Comment by Shazza-M-1993** [comment]
Ok i deleted all my addons, deleted the wtf, interface and cache files and reinstalled the addon on its own and nothing. Again its working in Raids, Instances but still not in Guild chat

**Comment by Shazza-M-1993** [comment]
Ok nevermind finally figured out what was wrong thank you for your support =)

**Comment by Shazza-M-1993** [comment]
i was a complete idiot who didnt realise that this addon only worked in the chat box. I thought it would also work in the Guild and Communities box. Basically I am a idiot

**Comment by Starlynk1** [comment]
Ahh, so you were typing in the Guild and Communities window. I will see what can be done to make it work there as well, not sure it can yet, but I will look into it as a Feature Request.
